baseURL = "https://future-hope.org"
buildDrafts = false
buildExpired = false
buildFuture = false
enableRobotsTXT = true
theme = "PaperMod"
title = "我的博客"

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 40

[minify]
disableXML = true
minifyOutput = true

[pagination]
pagerSize = 5

[params]
DateFormat = "2006-01-02"
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowReadingTime = true
ShowRssButtonInSectionTermList = true
ShowShareButtons = true
ShowWordCount = true
UseHugoToc = true
author = "你的名字"
comments = false
defaultTheme = "auto"
description = "分享生活，记录成长"
disableScrollToTop = false
disableSpecial1stPost = false
env = "production"
hideSummary = false
hidemeta = false
keywords = ["Blog", "Portfolio", "PaperMod"]
showtoc = true
title = "我的小天地"
tocopen = false

[params.profileMode]
enabled = false
imageHeight = 120
imageTitle = "profile image"
imageUrl = "#"
imageWidth = 120
subtitle = "欢迎访问我的博客"
title = "我的博客"

[[params.profileMode.buttons]]
name = "文章"
url = "posts"

[[params.profileMode.buttons]]
name = "标签"
url = "tags"

[[params.socialIcons]]
name = "github"
url = "https://github.com/yourusername"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/yourusername"
